server:
  port: 8000
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always # Ativa a saida em cores ANSI.
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    
resilience4j:
  circuitbreaker:
    instances:
      ticketsByUserCB:
      #https://resilience4j.readme.io/docs/circuitbreaker
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
                
      notificationsByUserCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    userExchange: users.v1.user_event
  key:
    userKey: users.v1.user_event.send_user.key
    
jwt:
  expiration: 3600000
  refreshExpiration: 86400000
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

springdoc:
  show-actuator: true
   
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  tracing:
    sampling:
      probability: 1.0
  #zipkin:
    #base-url: http://localhost:9411 

logging:
  level:
    com:
      gustavo:
        userservice: DEBUG
    #root: DEBUG
